// This file is auto-generated by @hey-api/openapi-ts

export { getLeaderboardLbGet, getQualificationsQualificationsGet, getRegionsRegionsGet, type Options, rootGet } from './sdk.gen';
export type { ClientOptions, GetLeaderboardLbGetData, GetLeaderboardLbGetError, GetLeaderboardLbGetErrors, GetLeaderboardLbGetResponses, GetQualificationsQualificationsGetData, GetQualificationsQualificationsGetResponses, GetRegionsRegionsGetData, GetRegionsRegionsGetResponses, HttpValidationError, Qualification, RootGetData, RootGetResponses, ValidationError } from './types.gen';
