// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetLeaderboardLbGetData, GetLeaderboardLbGetErrors, GetLeaderboardLbGetResponses, GetQualificationsQualificationsGetData, GetQualificationsQualificationsGetErrors, GetQualificationsQualificationsGetResponses, GetRegionsRegionsGetData, GetRegionsRegionsGetResponses, GetTeamsTeamsGetData, GetTeamsTeamsGetErrors, GetTeamsTeamsGetResponses, PutQualificationsQualificationsPutData, PutQualificationsQualificationsPutErrors, PutQualificationsQualificationsPutResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Teams
 */
export const getTeamsTeamsGet = <ThrowOnError extends boolean = false>(options: Options<GetTeamsTeamsGetData, ThrowOnError>) => (options.client ?? client).get<GetTeamsTeamsGetResponses, GetTeamsTeamsGetErrors, ThrowOnError>({ url: '/teams', ...options });

/**
 * Get Regions
 */
export const getRegionsRegionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetRegionsRegionsGetData, ThrowOnError>) => (options?.client ?? client).get<GetRegionsRegionsGetResponses, unknown, ThrowOnError>({ url: '/regions', ...options });

/**
 * Get Leaderboard
 */
export const getLeaderboardLbGet = <ThrowOnError extends boolean = false>(options?: Options<GetLeaderboardLbGetData, ThrowOnError>) => (options?.client ?? client).get<GetLeaderboardLbGetResponses, GetLeaderboardLbGetErrors, ThrowOnError>({ url: '/lb', ...options });

/**
 * Get Qualifications
 */
export const getQualificationsQualificationsGet = <ThrowOnError extends boolean = false>(options: Options<GetQualificationsQualificationsGetData, ThrowOnError>) => (options.client ?? client).get<GetQualificationsQualificationsGetResponses, GetQualificationsQualificationsGetErrors, ThrowOnError>({ url: '/qualifications', ...options });

/**
 * Put Qualifications
 */
export const putQualificationsQualificationsPut = <ThrowOnError extends boolean = false>(options: Options<PutQualificationsQualificationsPutData, ThrowOnError>) => (options.client ?? client).put<PutQualificationsQualificationsPutResponses, PutQualificationsQualificationsPutErrors, ThrowOnError>({ url: '/qualifications', ...options });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
