// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Qualification
 */
export type Qualification = 0 | 1 | 2;

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetTeamsTeamsGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         */
        authorization: string | null;
    };
    path?: never;
    query?: never;
    url: '/teams';
};

export type GetTeamsTeamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamsTeamsGetError = GetTeamsTeamsGetErrors[keyof GetTeamsTeamsGetErrors];

export type GetTeamsTeamsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLeaderboardLbGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Grade
         */
        grade?: string;
        /**
         * Region
         */
        region?: string | null;
        /**
         * Exclude Statuses
         */
        exclude_statuses?: Array<Qualification>;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/lb';
};

export type GetLeaderboardLbGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLeaderboardLbGetError = GetLeaderboardLbGetErrors[keyof GetLeaderboardLbGetErrors];

export type GetLeaderboardLbGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQualificationsQualificationsGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         */
        authorization: string | null;
    };
    path?: never;
    query?: never;
    url: '/qualifications';
};

export type GetQualificationsQualificationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQualificationsQualificationsGetError = GetQualificationsQualificationsGetErrors[keyof GetQualificationsQualificationsGetErrors];

export type GetQualificationsQualificationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PutQualificationsQualificationsPutData = {
    body?: never;
    headers: {
        /**
         * Authorization
         */
        authorization: string | null;
    };
    path?: never;
    query: {
        /**
         * Team
         */
        team: string;
        status: Qualification;
    };
    url: '/qualifications';
};

export type PutQualificationsQualificationsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutQualificationsQualificationsPutError = PutQualificationsQualificationsPutErrors[keyof PutQualificationsQualificationsPutErrors];

export type PutQualificationsQualificationsPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
